# Generated by Django 2.1.7 on 2020-01-21 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useraccount',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='useraccount',
            name='is_admin',
        ),
        migrations.RemoveField(
            model_name='useraccount',
            name='is_staff',
        ),
    ]
